service: ensyu3-2
provider: aws

plugins:
  - serverless-step-functions
  - serverless-plugin-typescript
  - serverless-pseudo-parameters
  
functions:
  helloFunc:
    name: helloFunc
    handler: src/myfunc.handler

stepFunctions:
  stateMachines:
    myStepFunction:
      name: MyStepFunc3-2
      definition:
        StartAt: HelloWorld
        States: 
          HelloWorld: 
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:helloFunc
            End: true
