service: ensyu4-0
provider: aws

resources:
  Resources:
    MyDynamoDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: MyTable
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
          -
            AttributeName: key
            AttributeType: S
          -
            AttributeName: value
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: key
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
