service: ensyu2-7
provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.profile.${self:custom.stage}.region}

plugins:
  - serverless-plugin-typescript

custom:
  stage: ${opt:stage, "dev"}
  profile:
    dev:
      region: ap-northeast-1
      message: This is dev stage.
    product:
      region: us-east-1
      message: This is product stage.

functions:
  hello:
    handler: src/myfunc.handler
    environment:
      message: ${self:custom.profile.${self:custom.stage}.message}
