version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres4peisma
    ports:
      - 5432:5432
    volumes:
      - ./db-data/postgres/init.d:/docker-entrypoint-initdb.docker
      - ./db-data/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
      POSTGRES_INITDB_ARG: '--encoding=UTF-8'
      POSTGRES_DB: mydatabase
    hostname: postgres
    restart: always
    user: root
## docker exec -it postgres psql -U udemy_user udemydb
