service: ensyu3-0
provider:
  name: aws


plugins:
  - serverless-step-functions

stepFunctions:
  stateMachines:
    myStepFunction:
      definition:
        StartAt: HelloWorld
        States: 
          HelloWorld: 
            Type: Pass
            Result: Hello, World!
            End: true
